### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/ZenVSCodeInstaller#1]
Not sure why there are separate Windows/MacOS instructions. It's just a matter of which install they download, yes?

(By the way, I just used platformio.org's link, but the link herein is probably more official...)

In Step 2, you can just click the extension manager icon on the left (the four squares with one broken out). Saves a click!

We should add Step 7) Upload. In particular, have them try to upload and if it doesn't work, send them to the ESP32 driver page. A lot of Windows machines needed drivers; as did one mac (but it was an older one).

Otherwise, looks good.

We could add "advanced" setup for those who want:
- know/want to learn how to use github? (have them fork the lib and clone it)
- want to try your hand at editing the lib? (have them fork and clone the lib; link to the local version) [this would need a giant DANGER sign, but some might want to try.]

**Comment by gcl8a** [comment]
I don't understand the macOS instructions. I don't know anyone who had trouble installing thought the usual suspects. Installing the cli can lead to other difficulties later on.

**Comment by madhephaestus** [comment]
It's required for the current OS, previous versions would install that on the fly.
