### ISSUE TITLE
Two pages

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/ZenVSCodeInstaller#4]
I'd reorganize into two pages: One for the base install and one for if they want to git. That way, they know where to stop for the basic install (and you don't have to say, "Don't do 4 and 5" -- you just take them to another page.

I like github desktop, but just to be clear: you can clone a repo from within VSCode pretty easily. Oh, wait. That won't install git, itself. Does GHDesktop install git?

**Comment by madhephaestus** [comment]
Yes, and it deals with the webflow api for gaining keys in order to push.

**Comment by madhephaestus** [comment]
the built in git integration works well for me on Linux, as i have git installed, and use SSH authentication for push/pull. As of Mid November the only other ways to push code to github is to use an application that implements WebFlow for gaining an application key, or generating tokens through the web interface and using that token in place of the password or generating SSH keys and posting the public key to GitHub (we do that one in 3001). SImple User/Password will no longer be allowed for pushing code to github. GitHub Desktop implements WebFlow and so avoids that coming issue. GitHub Desktop is also a LOT EASIER for new users and has much more complete documentation that is accessible for new users.

**Comment by gcl8a** [comment]
I don’t know about the token business, but I agree that GH Desktop is easier to use. I only recently started doing push/pulls from within VSCode. My normal workflow is local git from within VSC and then go to GHDesktop, where the changes are much clearer and I can be more sure of what I’m committing (which helps prevent my clobbering the  pin assignments…).

**Comment by madhephaestus** [comment]
Instructions should be ready for roll out if you want to take one last look over

**Comment by gcl8a** [comment]
You should explain in Step 3 the advantages/disadvantages of each of the options. e.g., “If you’re new to programming and want a simple install…”

“If you’re an experiences programmer or you want to get started using version control with git…”

Otherwise, they won’t know which one or the other they should do.

Also, since everyone is already set up in 1001, there is no rush for this. We’ll want to consolidate libraries over Break (so there’s no V2 and V3 optoins).

**Comment by madhephaestus** [comment]
I added the pro/con for example/git.

As for the v2/v3 section, that will be removed for C term, but is there for any current students. 

You might also want to use the Template repo i made and the git instructions this term for the final project. It is a template repo that can be forked to private of the RCCTL example and all the platformio.ini, .gitignore configs pre-set

**Comment by gcl8a** [comment]
That last part is up to Nick and Brad.

In C-term, I’d like to have all the examples in “standard” pio form, but that’s on me to get it all organized.

**Comment by madhephaestus** [comment]
Template repos might be a nice way of distributing that information. Each example would be a configured pio project for them to template off of. since its a template you can make as many forks as you want.
